# Generated by Django 4.1.6 on 2023-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
