# Generated by Django 4.1.6 on 2023-04-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
