# Generated by Django 4.1.6 on 2023-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_showtime_end_time_alter_showtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
