# Generated by Django 4.1.6 on 2023-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM', null=True),
        ),
    ]
