# Generated by Django 4.1.6 on 2023-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_showtime_end_time_alter_showtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]', null=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]', null=True),
        ),
    ]
