# Generated by Django 4.1.6 on 2023-04-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_showtime_end_time_alter_showtime_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='showtimeID',
            new_name='shownum',
        ),
    ]
