# Generated by Django 4.1.6 on 2023-04-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_cardtype_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promoCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
